name: actions
on:
  push:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  fedora:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        QEMU_VER: [v6.1.0-1]
        DOCKER_REPO: [docker.io/multiarch/fedora]
        LATEST_VERSION: [34]
        VERSION: [33, 34]
        TAG_ARCH: [x86_64, aarch64, s390x, ppc64le]
        include:
          - {ARCH: x86_64,  QEMU_ARCH: x86_64,  TAG_ARCH: x86_64}
          - {ARCH: aarch64, QEMU_ARCH: aarch64, TAG_ARCH: aarch64}
          - {ARCH: s390x,   QEMU_ARCH: s390x,   TAG_ARCH: s390x}
          - {ARCH: ppc64le, QEMU_ARCH: ppc64le, TAG_ARCH: ppc64le}
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends qemu-user-static
          sudo ./update.sh -a ${{ matrix.ARCH }} -v ${{ matrix.VERSION }} -q ${{ matrix.QEMU_ARCH }} -u ${{ matrix.QEMU_VER }} -d ${{ matrix.DOCKER_REPO }} -t ${{ matrix.TAG_ARCH }} -l ${{ matrix.LATEST_VERSION }}
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
          docker push -a ${{ matrix.DOCKER_REPO }}
